alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.devices enable row level security;
alter table public.devices force row level security;
alter table public.consent_records enable row level security;
alter table public.consent_records force row level security;
alter table public.monitoring_sessions enable row level security;
alter table public.monitoring_sessions force row level security;
alter table public.browser_events enable row level security;
alter table public.browser_events force row level security;
alter table public.screenshot_metadata enable row level security;
alter table public.screenshot_metadata force row level security;
alter table public.observations enable row level security;
alter table public.observations force row level security;
alter table public.activities enable row level security;
alter table public.activities force row level security;
alter table public.activity_event_links enable row level security;
alter table public.activity_event_links force row level security;
alter table public.session_summaries enable row level security;
alter table public.session_summaries force row level security;
alter table public.domain_rules enable row level security;
alter table public.domain_rules force row level security;
alter table public.observation_embeddings enable row level security;
alter table public.observation_embeddings force row level security;

create policy profiles_select_own on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy devices_select_own on public.devices for select to authenticated using ((select auth.uid()) = user_id);
create policy consent_records_select_own on public.consent_records for select to authenticated using ((select auth.uid()) = user_id);
create policy monitoring_sessions_select_own on public.monitoring_sessions for select to authenticated using ((select auth.uid()) = user_id);
create policy browser_events_select_own on public.browser_events for select to authenticated using ((select auth.uid()) = user_id);
create policy screenshot_metadata_select_own on public.screenshot_metadata for select to authenticated using ((select auth.uid()) = user_id);
create policy observations_select_own on public.observations for select to authenticated using ((select auth.uid()) = user_id);
create policy activities_select_own on public.activities for select to authenticated using ((select auth.uid()) = user_id);
create policy activity_event_links_select_own on public.activity_event_links for select to authenticated using ((select auth.uid()) = user_id);
create policy session_summaries_select_own on public.session_summaries for select to authenticated using ((select auth.uid()) = user_id);
create policy domain_rules_select_own on public.domain_rules for select to authenticated using (source = 'user' and (select auth.uid()) = user_id);
create policy observation_embeddings_select_own on public.observation_embeddings for select to authenticated using ((select auth.uid()) = user_id);

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke execute on all functions in schema public from public, anon, authenticated;
grant usage on schema public to authenticated;
grant select on public.profiles, public.devices, public.consent_records, public.monitoring_sessions, public.browser_events, public.screenshot_metadata, public.observations, public.activities, public.activity_event_links, public.session_summaries, public.domain_rules, public.observation_embeddings to authenticated;
